# Generated by Django 6.1 on 2026-09-17 17:50

import core.mixin.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(blank=True, choices=[('PLAN_TO_WATCH', 'Por ver'), ('AWAITING_RELEASE', 'Esperando estreno'), ('WATCHING', 'Viendo'), ('COMPLETED', 'Completado'), ('ON_HOLD', 'En pausa'), ('DROPPED', 'Abandonado'), ('DISLIKED', 'No me gustó'), ('DOWNLOADED', 'Descargado'), ('PURCHASED', 'Comprado')], max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'colección de anime',
                'verbose_name_plural': 'colecciones de anime',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArtistCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(blank=True, choices=[('PLAN_TO_LISTEN', 'Por escuchar'), ('LISTENING', 'Escuchando'), ('LISTENED', 'Escuchado'), ('DROPPED', 'Abandonado'), ('DISLIKED', 'No me gustó'), ('DOWNLOADED', 'Descargado'), ('PURCHASED', 'Comprado')], max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'colección de artistas',
                'verbose_name_plural': 'colecciones de artistas',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CharacterCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'colección de personajes',
                'verbose_name_plural': 'colecciones de personajes',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='momento')),
                ('process', models.CharField(blank=True, max_length=255, verbose_name='proceso')),
                ('level', models.CharField(choices=[('NOT_SET', 'No establecido'), ('TRACE', 'Rastreo'), ('DEBUG', 'Depuración'), ('INFO', 'Información'), ('NOTICE', 'Aviso'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico'), ('FATAL', 'Error fatal'), ('ALERT', 'Alerta'), ('EMERGENCY', 'Emergencia')], default='INFO', max_length=10, verbose_name='nivel')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'log de colecciones',
                'verbose_name_plural': 'logs de colecciones',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'colección de compañías',
                'verbose_name_plural': 'colecciones de compañías',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GameCharacterCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'colección de personajes de juego',
                'verbose_name_plural': 'colecciones de personajes de juego',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(blank=True, choices=[('PLAN_TO_PLAY', 'Por jugar'), ('AWAITING_RELEASE', 'Esperando lanzamiento'), ('PLAYING', 'Jugando'), ('COMPLETED', 'Completado'), ('PLATINUM', 'Platinado'), ('ON_HOLD', 'En pausa'), ('DROPPED', 'Abandonado'), ('DISLIKED', 'No me gustó'), ('DOWNLOADED', 'Descargado')], max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'colección de juegos',
                'verbose_name_plural': 'colecciones de juegos',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MangaCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(blank=True, choices=[('PLAN_TO_READ', 'Por leer'), ('READING', 'Leyendo'), ('COMPLETED', 'Completado'), ('AWAITING_CHAPTERS', 'Esperando capítulos'), ('ON_HOLD', 'En pausa'), ('DROPPED', 'Abandonado'), ('DISLIKED', 'No me gustó'), ('DOWNLOADED', 'Descargado'), ('PURCHASED', 'Comprado')], max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'colección de manga',
                'verbose_name_plural': 'colecciones de manga',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovieCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(blank=True, choices=[('PLAN_TO_WATCH', 'Por ver'), ('WATCHED', 'Vista'), ('REWATCH', 'Para revisitar'), ('DROPPED', 'Abandonada'), ('DISLIKED', 'No me gustó'), ('DOWNLOADED', 'Descargada'), ('PURCHASED', 'Comprada')], max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'colección de películas',
                'verbose_name_plural': 'colecciones de películas',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'colección de personas',
                'verbose_name_plural': 'colecciones de personas',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SerieCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(blank=True, choices=[('PLAN_TO_WATCH', 'Por ver'), ('AWAITING_PREMIERE', 'Esperando estreno'), ('WATCHING', 'Viendo'), ('COMPLETED', 'Completada'), ('ON_HOLD', 'En pausa'), ('DROPPED', 'Abandonada'), ('DISLIKED', 'No me gustó'), ('DOWNLOADED', 'Descargada'), ('PURCHASED', 'Comprada')], max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'colección de series',
                'verbose_name_plural': 'colecciones de series',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SongCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(blank=True, choices=[('PLAN_TO_LISTEN', 'Por escuchar'), ('LISTENING', 'Escuchando'), ('LISTENED', 'Escuchado'), ('DROPPED', 'Abandonado'), ('DISLIKED', 'No me gustó'), ('DOWNLOADED', 'Descargado'), ('PURCHASED', 'Comprado')], max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'colección de canciones',
                'verbose_name_plural': 'colecciones de canciones',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AlbumCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuación')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favorito')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='añadido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(blank=True, choices=[('PLAN_TO_LISTEN', 'Por escuchar'), ('LISTENING', 'Escuchando'), ('LISTENED', 'Escuchado'), ('DROPPED', 'Abandonado'), ('DISLIKED', 'No me gustó'), ('DOWNLOADED', 'Descargado'), ('PURCHASED', 'Comprado')], max_length=20, verbose_name='estado')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='music.album', verbose_name='álbum')),
                ('download_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga')),
                ('download_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga')),
                ('download_site', models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de')),
            ],
            options={
                'verbose_name': 'colección de álbumes',
                'verbose_name_plural': 'colecciones de álbumes',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
    ]
