# Generated by Django 6.1 on 2026-09-17 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('collections', '0001_initial'),
        ('companies', '0001_initial'),
        ('games', '0001_initial'),
        ('movies', '0001_initial'),
        ('music', '0001_initial'),
        ('otaku', '0001_initial'),
        ('people', '0001_initial'),
        ('series', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='albumcollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='animecollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='otaku.anime', verbose_name='anime'),
        ),
        migrations.AddField(
            model_name='animecollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='animecollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='animecollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='animecollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='animecollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='artistcollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='music.artist', verbose_name='artista'),
        ),
        migrations.AddField(
            model_name='artistcollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='artistcollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='artistcollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='artistcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='artistcollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='charactercollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='otaku.character', verbose_name='personaje'),
        ),
        migrations.AddField(
            model_name='charactercollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='charactercollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='charactercollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='charactercollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='charactercollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='companycollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='companies.company', verbose_name='compañía'),
        ),
        migrations.AddField(
            model_name='companycollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='companycollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='companycollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='companycollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='companycollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='gamecharactercollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='games.character', verbose_name='personaje de juego'),
        ),
        migrations.AddField(
            model_name='gamecharactercollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='gamecharactercollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='gamecharactercollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='gamecharactercollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='gamecharactercollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='games.game', verbose_name='juego'),
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='mangacollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='otaku.manga', verbose_name='manga'),
        ),
        migrations.AddField(
            model_name='mangacollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='mangacollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='mangacollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='mangacollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='mangacollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='movies.movie', verbose_name='película'),
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='moviecollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='personcollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='people.person', verbose_name='persona'),
        ),
        migrations.AddField(
            model_name='personcollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='personcollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='personcollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='personcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='personcollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='seriecollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='series.serie', verbose_name='serie'),
        ),
        migrations.AddField(
            model_name='seriecollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='seriecollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='seriecollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='seriecollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='seriecollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddField(
            model_name='songcollection',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='music.song', verbose_name='canción'),
        ),
        migrations.AddField(
            model_name='songcollection',
            name='download_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.format', verbose_name='formato de descarga'),
        ),
        migrations.AddField(
            model_name='songcollection',
            name='download_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloads', to='catalogs.quality', verbose_name='calidad de descarga'),
        ),
        migrations.AddField(
            model_name='songcollection',
            name='download_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'descarga'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_downloaded', to='catalogs.website', verbose_name='lo descargué de'),
        ),
        migrations.AddField(
            model_name='songcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='songcollection',
            name='watch_site',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'streaming'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_watched', to='catalogs.website', verbose_name='lo veo en'),
        ),
        migrations.AddConstraint(
            model_name='albumcollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_album_collection'),
        ),
        migrations.AddConstraint(
            model_name='animecollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_anime_collection'),
        ),
        migrations.AddConstraint(
            model_name='artistcollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_artist_collection'),
        ),
        migrations.AddConstraint(
            model_name='charactercollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_character_collection'),
        ),
        migrations.AddConstraint(
            model_name='companycollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_company_collection'),
        ),
        migrations.AddConstraint(
            model_name='gamecharactercollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_game_character_collection'),
        ),
        migrations.AddConstraint(
            model_name='gamecollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_game_collection'),
        ),
        migrations.AddConstraint(
            model_name='mangacollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_manga_collection'),
        ),
        migrations.AddConstraint(
            model_name='moviecollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_movie_collection'),
        ),
        migrations.AddConstraint(
            model_name='personcollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_person_collection'),
        ),
        migrations.AddConstraint(
            model_name='seriecollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_serie_collection'),
        ),
        migrations.AddConstraint(
            model_name='songcollection',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='uniq_song_collection'),
        ),
    ]
