"""Vistas de games como PAQUETE plano (estilo Poseidón): base.py (mixins _Base<Modelo>, mapas _BaseXBy y helpers) y un
archivo por rol con las DOS caras, gestión y público. Este __init__ SOLO re-exporta: `from apps.games import views`
(urls/public.py) y `views as v` (urls/panel.py, urls/data.py) siguen funcionando y cada clase tiene UN archivo dueño."""
from apps.games.views.v1_home import GamesHomeView, GamesPublicHomeView  # noqa: F401,E402
from apps.games.views.v2_filters import GameFilters, CreatorFilters, CharacterFilters, ReleaseFilters  # noqa: F401,E402
from apps.games.views.v3_data import GameDataView, GameSelectView, CreatorDataView, CreatorSelectView, GenreDataView, GenreSelectView, DevelopmentEngineDataView, DevelopmentEngineSelectView, PlatformDataView, PlatformSelectView, MediumDataView, MediumSelectView, CreatorNicknameDataView, CreatorNicknameSelectView, GameTitleDataView, GameTitleSelectView, GameImageDataView, GameImageSelectView, CreatorLinkDataView, CreatorLinkSelectView, GameLinkDataView, GameLinkSelectView, GameLogDataView, DataVndbGameDataView, DataVndbCreatorDataView, DataVndbReleaseDataView, DataVndbCharacterDataView, DataF95GameDataView, DataF95CreatorDataView, CharacterDataView, CharacterSelectView, CharacterRoleDataView, CharacterImageDataView, ReleaseDataView, GamePublicDataView, CreatorPublicDataView, PublisherPublicDataView, CharacterPublicDataView, ReleasePublicDataView, GameImagesPublicDataView, TagDataView, GenreAliasDataView, TagAliasDataView, ReleaseImageDataView  # noqa: F401,E402
from apps.games.views.v4_write import GameCreateView, GameUpdateView, GameDeleteView, CreatorCreateView, CreatorUpdateView, CreatorDeleteView, GenreCreateView, GenreUpdateView, GenreDeleteView, DevelopmentEngineCreateView, DevelopmentEngineUpdateView, DevelopmentEngineDeleteView, PlatformCreateView, PlatformUpdateView, PlatformDeleteView, MediumCreateView, MediumUpdateView, MediumDeleteView, CreatorNicknameCreateView, CreatorNicknameUpdateView, CreatorNicknameDeleteView, GameTitleCreateView, GameTitleUpdateView, GameTitleDeleteView, GameImageCreateView, GameImageUpdateView, GameImageDeleteView, CreatorLinkCreateView, CreatorLinkUpdateView, CreatorLinkDeleteView, GameLinkCreateView, GameLinkUpdateView, GameLinkDeleteView, CharacterCreateView, CharacterUpdateView, CharacterDeleteView, CharacterRoleCreateView, CharacterRoleUpdateView, CharacterRoleDeleteView, CharacterImageCreateView, CharacterImageUpdateView, CharacterImageDeleteView, ReleaseCreateView, ReleaseUpdateView, ReleaseDeleteView, DataVndbGameUpdateView, DataVndbGameDeleteView, DataVndbCreatorUpdateView, DataVndbCreatorDeleteView, DataVndbReleaseUpdateView, DataVndbReleaseDeleteView, DataVndbCharacterUpdateView, DataVndbCharacterDeleteView, DataF95GameUpdateView, DataF95GameDeleteView, DataF95CreatorUpdateView, DataF95CreatorDeleteView, GameLogCreateView, GameLogUpdateView, GameLogDeleteView, DataVndbCharacterCreateView, DataVndbCreatorCreateView, DataF95GameCreateView, DataF95CreatorCreateView, DataVndbGameCreateView, DataVndbReleaseCreateView, TagCreateView, TagUpdateView, TagDeleteView, GenreAliasCreateView, GenreAliasUpdateView, GenreAliasDeleteView, TagAliasCreateView, TagAliasUpdateView, TagAliasDeleteView, ReleaseImageCreateView, ReleaseImageUpdateView, ReleaseImageDeleteView  # noqa: F401,E402
from apps.games.views.v5_list import GameListView, CreatorListView, GenreListView, DevelopmentEngineListView, PlatformListView, MediumListView, CreatorNicknameListView, GameTitleListView, GameImageListView, CreatorLinkListView, GameLinkListView, GameLogListView, DataVndbGameListView, DataVndbCreatorListView, DataVndbReleaseListView, DataVndbCharacterListView, DataF95GameListView, DataF95CreatorListView, CharacterListView, CharacterRoleListView, CharacterImageListView, ReleaseListView, GamePublicListView, CreatorPublicListView, PublisherPublicListView, TagListView, GenreAliasListView, TagAliasListView, GenreAliasListByView, TagAliasListByView, ReleaseImageListView, ReleaseImageListByView  # noqa: F401,E402
from apps.games.views.v5_list_by import CreatorPublicListByView, GamePublicListByView, CharacterPublicListByView, GameImagePublicListByView, ReleasePublicListByView, CreatorListByView, CreatorLinkListByView, CreatorNicknameListByView, GameListByView, CharacterListByView, CharacterImageListByView, CharacterRoleListByView, GameImageListByView, GameLinkListByView, ReleaseListByView, GameTitleListByView  # noqa: F401,E402
from apps.games.views.v6_detail import GameDetailView, CreatorDetailView, GenreDetailView, DevelopmentEngineDetailView, PlatformDetailView, MediumDetailView, CreatorNicknameDetailView, GameTitleDetailView, GameImageDetailView, CreatorLinkDetailView, GameLinkDetailView, GameLogDetailView, DataVndbGameDetailView, DataVndbCreatorDetailView, DataVndbReleaseDetailView, DataVndbCharacterDetailView, DataF95GameDetailView, DataF95CreatorDetailView, CharacterDetailView, CharacterRoleDetailView, CharacterImageDetailView, ReleaseDetailView, GamePublicDetailView, CreatorPublicDetailView, CharacterPublicDetailView, TagDetailView, GenreAliasDetailView, TagAliasDetailView, ReleaseImageDetailView  # noqa: F401,E402
from apps.games.views.v8_import import (  # noqa: F401,E402 — importación VNDB: una vista por tabla Data
    LoadVNDBDataF95GameView, LoadVNDBDataF95GameSearchView, LoadVNDBDataCreatorView, LoadVNDBDataCreatorSearchView,
    LoadVNDBDataReleaseView, LoadVNDBDataReleaseSearchView, LoadVNDBDataCharacterView, LoadVNDBDataCharacterSearchView,
    VNDBProcessPendingView, ProcessVndbCharacterView, ProcessVndbCreatorView, ProcessVndbGameView, ProcessVndbReleaseView, VNDBTagsLoadView, VNDBTagsSummaryView)
from apps.games.views.v8_images import CharacterImageDownloadView, GameImageDownloadView, ReleaseImageDownloadView  # noqa: F401,E402
