"""Vistas de movies como PAQUETE plano (estilo Poseidón): base.py (mixins _Base<Modelo>, mapas _BaseXBy y helpers) y un
archivo por rol con las DOS caras, gestión y público. Este __init__ SOLO re-exporta: `from apps.movies import views`
(urls/public.py) y `views as v` (urls/panel.py, urls/data.py) siguen funcionando y cada clase tiene UN archivo dueño."""
from apps.movies.views.v1_home import MoviesHomeView, MoviesPublicHomeView  # noqa: F401,E402
from apps.movies.views.v2_filters import MovieFilters, CompanyFilters, MovieCastFilters, MovieStaffFilters, RoleFilters  # noqa: F401,E402
from apps.movies.views.v3_data import MovieDataView, MovieSelectView, GenreDataView, GenreSelectView, TypeDataView, TypeSelectView, RatingDataView, RatingSelectView, MovieCastDataView, MovieCastSelectView, MovieRelationDataView, MovieRelationSelectView, MovieStaffDataView, MovieStaffSelectView, RoleDataView, RoleSelectView, MovieTitleDataView, MovieTitleSelectView, MovieImageDataView, MovieImageSelectView, MovieLogDataView, MoviePublicDataView, ProducerPublicDataView, DistributorPublicDataView, MovieCastPublicDataView, MovieStaffPublicDataView, MovieImagesPublicDataView, GenreAliasDataView  # noqa: F401,E402
from apps.movies.views.v4_write import MovieCreateView, MovieUpdateView, MovieDeleteView, GenreCreateView, GenreUpdateView, GenreDeleteView, TypeCreateView, TypeUpdateView, TypeDeleteView, RatingCreateView, RatingUpdateView, RatingDeleteView, MovieCastCreateView, MovieCastUpdateView, MovieCastDeleteView, MovieRelationCreateView, MovieRelationUpdateView, MovieRelationDeleteView, MovieStaffCreateView, MovieStaffUpdateView, MovieStaffDeleteView, RoleCreateView, RoleUpdateView, RoleDeleteView, MovieTitleCreateView, MovieTitleUpdateView, MovieTitleDeleteView, MovieImageCreateView, MovieImageUpdateView, MovieImageDeleteView, MovieLogCreateView, MovieLogUpdateView, MovieLogDeleteView, GenreAliasCreateView, GenreAliasUpdateView, GenreAliasDeleteView  # noqa: F401,E402
from apps.movies.views.v5_list import MovieListView, GenreListView, TypeListView, RatingListView, MovieCastListView, MovieRelationListView, MovieStaffListView, RoleListView, MovieTitleListView, MovieImageListView, MovieLogListView, MoviePublicListView, ProducerPublicListView, DistributorPublicListView, RoleListByView, GenreAliasListView, GenreAliasListByView  # noqa: F401,E402
from apps.movies.views.v5_list_by import MoviePublicListByView, MovieCastPublicListByView, MovieImagePublicListByView, MovieStaffPublicListByView, MovieListByView, MovieCastListByView, MovieImageListByView, MovieRelationListByView, MovieStaffListByView, MovieTitleListByView  # noqa: F401,E402
from apps.movies.views.v6_detail import MovieDetailView, GenreDetailView, TypeDetailView, RatingDetailView, MovieCastDetailView, MovieRelationDetailView, MovieStaffDetailView, RoleDetailView, MovieTitleDetailView, MovieImageDetailView, MovieLogDetailView, MoviePublicDetailView, GenreAliasDetailView  # noqa: F401,E402
from apps.movies.views.v8_images import MovieImageDownloadView  # noqa: F401,E402
