# Generated by Django 6.1 on 2026-09-17 17:50

import core.mixin.models
import core.shared.models.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='momento')),
                ('process', models.CharField(blank=True, max_length=255, verbose_name='proceso')),
                ('level', models.CharField(choices=[('NOT_SET', 'No establecido'), ('TRACE', 'Rastreo'), ('DEBUG', 'Depuración'), ('INFO', 'Información'), ('NOTICE', 'Aviso'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico'), ('FATAL', 'Error fatal'), ('ALERT', 'Alerta'), ('EMERGENCY', 'Emergencia')], default='INFO', max_length=10, verbose_name='nivel')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'log de personas',
                'verbose_name_plural': 'logs de personas',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='nombre completo')),
                ('biography', models.TextField(blank=True, verbose_name='biografía')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='inicial')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=270, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='catalogs.country', verbose_name='país')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['full_name'],
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='orden')),
                ('image_url', models.TextField(blank=True, verbose_name='URL de la imagen')),
                ('image_downloaded', models.BooleanField(default=False, verbose_name='descargada')),
                ('download_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos de descarga')),
                ('download_error', models.CharField(blank=True, max_length=300, verbose_name='error de descarga')),
                ('download_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='último intento')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.shared.models.uploads.upload_path, verbose_name='imagen')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='people.person', verbose_name='persona')),
            ],
            options={
                'verbose_name': 'imagen de persona',
                'verbose_name_plural': 'imágenes de persona',
                'ordering': ['person', 'order', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['image_downloaded', 'download_attempts'], name='people_personimage_dl')],
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=500, verbose_name='id externo')),
                ('url', models.TextField(blank=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='people.person', verbose_name='persona')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='catalogs.externalsource', verbose_name='fuente')),
            ],
            options={
                'verbose_name': 'enlace de persona',
                'verbose_name_plural': 'enlaces de persona',
                'ordering': ['person', 'source'],
                'abstract': False,
                'unique_together': {('person', 'source', 'external_id')},
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='apodo')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicknames', to='people.person', verbose_name='persona')),
            ],
            options={
                'verbose_name': 'apodo de persona',
                'verbose_name_plural': 'apodos de persona',
                'ordering': ['nickname'],
                'abstract': False,
                'unique_together': {('person', 'nickname')},
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
    ]
