"""Vistas de series como PAQUETE plano (estilo Poseidón): base.py (mixins _Base<Modelo>, mapas _BaseXBy y helpers) y un
archivo por rol con las DOS caras, gestión y público. Este __init__ SOLO re-exporta: `from apps.series import views`
(urls/public.py) y `views as v` (urls/panel.py, urls/data.py) siguen funcionando y cada clase tiene UN archivo dueño."""
from apps.series.views.v1_home import SeriesHomeView, SeriesPublicHomeView  # noqa: F401,E402
from apps.series.views.v2_filters import SerieFilters, CompanyFilters, SerieCastFilters, SerieStaffFilters, RoleFilters  # noqa: F401,E402
from apps.series.views.v3_data import SerieDataView, SerieSelectView, GenreDataView, GenreSelectView, TypeDataView, TypeSelectView, RatingDataView, RatingSelectView, SerieCastDataView, SerieCastSelectView, SerieRelationDataView, SerieRelationSelectView, SerieStaffDataView, SerieStaffSelectView, RoleDataView, RoleSelectView, SerieTitleDataView, SerieTitleSelectView, SerieImageDataView, SerieImageSelectView, SerieLogDataView, SeriePublicDataView, ProducerPublicDataView, DistributorPublicDataView, SerieCastPublicDataView, SerieStaffPublicDataView, SerieImagesPublicDataView, GenreAliasDataView  # noqa: F401,E402
from apps.series.views.v4_write import SerieCreateView, SerieUpdateView, SerieDeleteView, GenreCreateView, GenreUpdateView, GenreDeleteView, TypeCreateView, TypeUpdateView, TypeDeleteView, RatingCreateView, RatingUpdateView, RatingDeleteView, SerieCastCreateView, SerieCastUpdateView, SerieCastDeleteView, SerieRelationCreateView, SerieRelationUpdateView, SerieRelationDeleteView, SerieStaffCreateView, SerieStaffUpdateView, SerieStaffDeleteView, RoleCreateView, RoleUpdateView, RoleDeleteView, SerieTitleCreateView, SerieTitleUpdateView, SerieTitleDeleteView, SerieImageCreateView, SerieImageUpdateView, SerieImageDeleteView, SerieLogCreateView, SerieLogUpdateView, SerieLogDeleteView, GenreAliasCreateView, GenreAliasUpdateView, GenreAliasDeleteView  # noqa: F401,E402
from apps.series.views.v5_list import SerieListView, GenreListView, TypeListView, RatingListView, SerieCastListView, SerieRelationListView, SerieStaffListView, RoleListView, SerieTitleListView, SerieImageListView, SerieLogListView, SeriePublicListView, ProducerPublicListView, DistributorPublicListView, RoleListByView, GenreAliasListView, GenreAliasListByView  # noqa: F401,E402
from apps.series.views.v5_list_by import SeriePublicListByView, SerieCastPublicListByView, SerieImagePublicListByView, SerieStaffPublicListByView, SerieListByView, SerieCastListByView, SerieImageListByView, SerieRelationListByView, SerieStaffListByView, SerieTitleListByView  # noqa: F401,E402
from apps.series.views.v6_detail import SerieDetailView, GenreDetailView, TypeDetailView, RatingDetailView, SerieCastDetailView, SerieRelationDetailView, SerieStaffDetailView, RoleDetailView, SerieTitleDetailView, SerieImageDetailView, SerieLogDetailView, SeriePublicDetailView, GenreAliasDetailView  # noqa: F401,E402
from apps.series.views.v8_images import SerieImageDownloadView  # noqa: F401,E402
