# Generated by Django 6.1 on 2026-09-17 17:50

import core.mixin.models
import core.shared.models.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='momento')),
                ('process', models.CharField(blank=True, max_length=255, verbose_name='proceso')),
                ('level', models.CharField(choices=[('NOT_SET', 'No establecido'), ('TRACE', 'Rastreo'), ('DEBUG', 'Depuración'), ('INFO', 'Información'), ('NOTICE', 'Aviso'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico'), ('FATAL', 'Error fatal'), ('ALERT', 'Alerta'), ('EMERGENCY', 'Emergencia')], default='INFO', max_length=10, verbose_name='nivel')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'log de compañías',
                'verbose_name_plural': 'logs de compañías',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=270, unique=True, verbose_name='slug')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año de fundación')),
                ('disolved_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año de disolución')),
                ('biography', models.TextField(blank=True, verbose_name='biografía')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='catalogs.country', verbose_name='país')),
            ],
            options={
                'verbose_name': 'compañía',
                'verbose_name_plural': 'compañías',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='orden')),
                ('image_url', models.TextField(blank=True, verbose_name='URL de la imagen')),
                ('image_downloaded', models.BooleanField(default=False, verbose_name='descargada')),
                ('download_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos de descarga')),
                ('download_error', models.CharField(blank=True, max_length=300, verbose_name='error de descarga')),
                ('download_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='último intento')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.shared.models.uploads.upload_path, verbose_name='imagen')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='companies.company', verbose_name='compañía')),
            ],
            options={
                'verbose_name': 'imagen de compañía',
                'verbose_name_plural': 'imágenes de compañía',
                'ordering': ['company', 'order', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['image_downloaded', 'download_attempts'], name='companies_companyimage_dl')],
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
    ]
