# Generated by Django 6.1 on 2026-09-17 17:50

import core.mixin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='archivo')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='subido')),
            ],
            options={
                'verbose_name': 'archivo en la nube',
                'verbose_name_plural': 'archivos en la nube',
                'ordering': ['-uploaded_at'],
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('task', models.CharField(max_length=255, verbose_name='tarea')),
                ('args', models.JSONField(blank=True, default=list, verbose_name='argumentos')),
                ('kwargs', models.JSONField(blank=True, default=dict, verbose_name='argumentos con nombre')),
                ('every_minutes', models.PositiveIntegerField(default=30, verbose_name='cada N minutos')),
                ('at_time', models.TimeField(blank=True, null=True, verbose_name='a esta hora')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='última ejecución')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='próxima ejecución')),
                ('last_task_id', models.CharField(blank=True, max_length=64, verbose_name='última tarea')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'tarea programada',
                'verbose_name_plural': 'tareas programadas',
                'ordering': ['name'],
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64, unique=True, verbose_name='id de tarea')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='tarea')),
                ('args', models.TextField(blank=True, verbose_name='argumentos')),
                ('status', models.CharField(choices=[('QUEUED', 'En cola'), ('RUNNING', 'Ejecutando'), ('DONE', 'Terminada'), ('FAILED', 'Fallida'), ('CANCELLED', 'Cancelada')], db_index=True, default='QUEUED', max_length=12, verbose_name='estado')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name='cancelación pedida')),
                ('result', models.TextField(blank=True, verbose_name='resultado / error')),
                ('queued_at', models.DateTimeField(auto_now_add=True, verbose_name='encolada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['-queued_at'],
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImportCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('anilist', 'AniList'), ('deezer', 'Deezer'), ('vndb', 'VNDB')], max_length=20, verbose_name='fuente')),
                ('type', models.CharField(max_length=30, verbose_name='tipo')),
                ('next_id', models.PositiveIntegerField(default=1, verbose_name='próximo id')),
                ('batch_size', models.PositiveIntegerField(default=100, verbose_name='cantidad por lote')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'cursor de lote',
                'verbose_name_plural': 'cursores de lote',
                'ordering': ['source', 'type'],
                'unique_together': {('source', 'type')},
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
    ]
