# Generated by Django 6.1 on 2026-09-17 17:50

import core.mixin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='momento')),
                ('process', models.CharField(blank=True, max_length=255, verbose_name='proceso')),
                ('level', models.CharField(choices=[('NOT_SET', 'No establecido'), ('TRACE', 'Rastreo'), ('DEBUG', 'Depuración'), ('INFO', 'Información'), ('NOTICE', 'Aviso'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico'), ('FATAL', 'Error fatal'), ('ALERT', 'Alerta'), ('EMERGENCY', 'Emergencia')], default='INFO', max_length=10, verbose_name='nivel')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'log de catálogos',
                'verbose_name_plural': 'logs de catálogos',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('name_esp', models.CharField(blank=True, max_length=100, verbose_name='nombre (ES)')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, upload_to='categorias/', verbose_name='imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('code', models.CharField(blank=True, max_length=4, verbose_name='código ISO')),
                ('numeric_code', models.PositiveIntegerField(default=0, verbose_name='código numérico')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('name_esp', models.CharField(blank=True, max_length=100, verbose_name='nombre (ES)')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, upload_to='categorias/', verbose_name='imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('acronym', models.CharField(blank=True, max_length=15, verbose_name='acrónimo')),
                ('url', models.URLField(blank=True, max_length=300, verbose_name='URL base')),
                ('type', models.CharField(choices=[('SOCIAL', 'Red social'), ('MONETIZATION', 'Monetización'), ('COMMUNITY', 'Comunidad'), ('OFFICIAL', 'Sitio oficial'), ('DATABASE', 'Base de datos'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'fuente externa',
                'verbose_name_plural': 'fuentes externas',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('name_esp', models.CharField(blank=True, max_length=100, verbose_name='nombre (ES)')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, upload_to='categorias/', verbose_name='imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('for_video', models.BooleanField(default=False, verbose_name='para vídeo')),
                ('for_music', models.BooleanField(default=False, verbose_name='para música')),
                ('for_image', models.BooleanField(default=False, verbose_name='para imagen')),
                ('for_document', models.BooleanField(default=False, verbose_name='para documento')),
                ('for_other', models.BooleanField(default=False, verbose_name='para otro')),
            ],
            options={
                'verbose_name': 'formato',
                'verbose_name_plural': 'formatos',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('name_esp', models.CharField(blank=True, max_length=100, verbose_name='nombre (ES)')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, upload_to='categorias/', verbose_name='imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('acronym', models.CharField(blank=True, max_length=10, verbose_name='acrónimo')),
                ('iso_639_1', models.CharField(blank=True, max_length=10, verbose_name='ISO 639-1')),
                ('iso_639_2_t', models.CharField(blank=True, max_length=10, verbose_name='ISO 639-2/T')),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idiomas',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('name_esp', models.CharField(blank=True, max_length=100, verbose_name='nombre (ES)')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, upload_to='categorias/', verbose_name='imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'calidad',
                'verbose_name_plural': 'calidades',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('name_esp', models.CharField(blank=True, max_length=100, verbose_name='nombre (ES)')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, upload_to='categorias/', verbose_name='imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'tipo de relación',
                'verbose_name_plural': 'tipos de relación',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('name_esp', models.CharField(blank=True, max_length=100, verbose_name='nombre (ES)')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, upload_to='categorias/', verbose_name='imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('acronym', models.CharField(blank=True, max_length=15, verbose_name='acrónimo')),
                ('url', models.URLField(blank=True, max_length=300, verbose_name='URL base')),
                ('type', models.CharField(choices=[('STREAMING', 'Streaming'), ('DOWNLOAD', 'Descarga'), ('STORE', 'Tienda'), ('DATABASE', 'Base de datos'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='tipo')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='inicial')),
            ],
            options={
                'verbose_name': 'sitio web',
                'verbose_name_plural': 'sitios web',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
    ]
