"""Vistas de catalogs como PAQUETE plano (estilo Poseidón): base.py (mixins _Base<Modelo>, mapas _BaseXBy y helpers) y un
archivo por rol con las DOS caras, gestión y público. Este __init__ SOLO re-exporta: `from apps.catalogs import views`
(urls/public.py) y `views as v` (urls/panel.py, urls/data.py) siguen funcionando y cada clase tiene UN archivo dueño."""
from apps.catalogs.views.v1_home import CatalogsHomeView  # noqa: F401,E402
from apps.catalogs.views.v2_filters import CountryFilters, LanguageFilters, FormatFilters, QualityFilters, WebsiteFilters, ExternalSourceFilters, RelationTypeFilters  # noqa: F401,E402
from apps.catalogs.views.v3_data import CountryDataView, CountrySelectView, LanguageDataView, LanguageSelectView, FormatDataView, FormatSelectView, QualityDataView, QualitySelectView, WebsiteDataView, WebsiteSelectView, ExternalSourceDataView, ExternalSourceSelectView, CatalogsLogDataView, RelationTypeDataView, RelationTypeSelectView, CAT_COLUMNS, CAT_SEARCH, OST_COLUMNS  # noqa: F401,E402
from apps.catalogs.views.v4_write import CountryCreateView, CountryUpdateView, CountryDeleteView, LanguageCreateView, LanguageUpdateView, LanguageDeleteView, FormatCreateView, FormatUpdateView, FormatDeleteView, QualityCreateView, QualityUpdateView, QualityDeleteView, WebsiteCreateView, WebsiteUpdateView, WebsiteDeleteView, ExternalSourceCreateView, ExternalSourceUpdateView, ExternalSourceDeleteView, RelationTypeCreateView, RelationTypeUpdateView, RelationTypeDeleteView, CatalogsLogCreateView, CatalogsLogUpdateView, CatalogsLogDeleteView  # noqa: F401,E402
from apps.catalogs.views.v5_list import CountryListView, LanguageListView, FormatListView, QualityListView, WebsiteListView, ExternalSourceListView, CatalogsLogListView, RelationTypeListView, WebsiteListByView, ExternalSourceListByView  # noqa: F401,E402
from apps.catalogs.views.v6_detail import CountryDetailView, LanguageDetailView, FormatDetailView, QualityDetailView, WebsiteDetailView, ExternalSourceDetailView, CatalogsLogDetailView, RelationTypeDetailView  # noqa: F401,E402
