"""Vistas de music como PAQUETE plano (estilo Poseidón): base.py (mixins _Base<Modelo>, mapas _BaseXBy y helpers) y un
archivo por rol con las DOS caras, gestión y público. Este __init__ SOLO re-exporta: `from apps.music import views`
(urls/public.py) y `views as v` (urls/panel.py, urls/data.py) siguen funcionando y cada clase tiene UN archivo dueño."""
from apps.music.views.v1_home import MusicHomeView, MusicPublicHomeView  # noqa: F401,E402
from apps.music.views.v2_filters import ArtistAdminFilters, ArtistFilters, AlbumFilters, SongFilters, ArtistSongFilters, RoleFilters  # noqa: F401,E402
from apps.music.views.v3_data import ArtistDataView, ArtistSelectView, AlbumDataView, AlbumSelectView, SongDataView, SongSelectView, GenreDataView, GenreSelectView, AlbumTypeDataView, AlbumTypeSelectView, ArtistTypeDataView, ArtistTypeSelectView, RoleDataView, RoleSelectView, ArtistMemberDataView, ArtistMemberSelectView, ArtistImageDataView, ArtistImageSelectView, AlbumImageDataView, AlbumImageSelectView, SongTranslationDataView, SongTranslationSelectView, SongComposerDataView, SongComposerSelectView, MusicLogDataView, DataDeezerArtistDataView, DataDeezerAlbumDataView, DataDeezerTrackDataView, DataDeezerGenreDataView, ArtistPublicDataView, AlbumPublicDataView, SongPublicDataView, AlbumImagesPublicDataView, ArtistImagesPublicDataView, GenreAliasDataView  # noqa: F401,E402
from apps.music.views.v4_write import ArtistCreateView, ArtistUpdateView, ArtistDeleteView, AlbumCreateView, AlbumUpdateView, AlbumDeleteView, SongCreateView, SongUpdateView, SongDeleteView, GenreCreateView, GenreUpdateView, GenreDeleteView, AlbumTypeCreateView, AlbumTypeUpdateView, AlbumTypeDeleteView, ArtistTypeCreateView, ArtistTypeUpdateView, ArtistTypeDeleteView, RoleCreateView, RoleUpdateView, RoleDeleteView, ArtistMemberCreateView, ArtistMemberUpdateView, ArtistMemberDeleteView, ArtistImageCreateView, ArtistImageUpdateView, ArtistImageDeleteView, AlbumImageCreateView, AlbumImageUpdateView, AlbumImageDeleteView, SongTranslationCreateView, SongTranslationUpdateView, SongTranslationDeleteView, SongComposerCreateView, SongComposerUpdateView, SongComposerDeleteView, DataDeezerArtistUpdateView, DataDeezerArtistDeleteView, DataDeezerAlbumUpdateView, DataDeezerAlbumDeleteView, DataDeezerTrackUpdateView, DataDeezerTrackDeleteView, DataDeezerGenreUpdateView, DataDeezerGenreDeleteView, MusicLogCreateView, MusicLogUpdateView, MusicLogDeleteView, DataDeezerAlbumCreateView, DataDeezerTrackCreateView, DataDeezerArtistCreateView, DataDeezerGenreCreateView, GenreAliasCreateView, GenreAliasUpdateView, GenreAliasDeleteView  # noqa: F401,E402
from apps.music.views.v5_list import ArtistListView, AlbumListView, SongListView, GenreListView, AlbumTypeListView, ArtistTypeListView, RoleListView, ArtistMemberListView, ArtistImageListView, AlbumImageListView, SongTranslationListView, SongComposerListView, MusicLogListView, DataDeezerArtistListView, DataDeezerAlbumListView, DataDeezerTrackListView, DataDeezerGenreListView, ArtistPublicListView, AlbumPublicListView, SongPublicListView, RoleListByView, GenreAliasListView, GenreAliasListByView  # noqa: F401,E402
from apps.music.views.v5_list_by import AlbumPublicListByView, AlbumImagePublicListByView, ArtistPublicListByView, ArtistImagePublicListByView, SongPublicListByView, AlbumListByView, AlbumImageListByView, ArtistListByView, ArtistImageListByView, ArtistMemberListByView, SongListByView, SongComposerListByView, SongTranslationListByView  # noqa: F401,E402
from apps.music.views.v6_detail import ArtistDetailView, AlbumDetailView, SongDetailView, GenreDetailView, AlbumTypeDetailView, ArtistTypeDetailView, RoleDetailView, ArtistMemberDetailView, ArtistImageDetailView, AlbumImageDetailView, SongTranslationDetailView, SongComposerDetailView, MusicLogDetailView, DataDeezerArtistDetailView, DataDeezerAlbumDetailView, DataDeezerTrackDetailView, DataDeezerGenreDetailView, ArtistPublicDetailView, AlbumPublicDetailView, SongPublicDetailView, GenreAliasDetailView  # noqa: F401,E402
from apps.music.views.v8_import import (  # noqa: F401,E402 — importación Deezer: una vista por tabla Data
    LoadDeezerDataArtistView, LoadDeezerDataArtistSearchView, LoadDeezerGenreView, DeezerProcessPendingView)
from apps.music.views.v8_images import AlbumImageDownloadView, ArtistImageDownloadView  # noqa: F401,E402
