# Generated by Django 6.1 on 2026-09-17 17:50

import core.mixin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('body', models.TextField(verbose_name='contenido')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'sección de nosotros',
                'verbose_name_plural': 'secciones de nosotros',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
            bases=(core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, core.mixin.models.CoverMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PagesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='momento')),
                ('process', models.CharField(blank=True, max_length=255, verbose_name='proceso')),
                ('level', models.CharField(choices=[('NOT_SET', 'No establecido'), ('TRACE', 'Rastreo'), ('DEBUG', 'Depuración'), ('INFO', 'Información'), ('NOTICE', 'Aviso'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico'), ('FATAL', 'Error fatal'), ('ALERT', 'Alerta'), ('EMERGENCY', 'Emergencia')], default='INFO', max_length=10, verbose_name='nivel')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'log de páginas',
                'verbose_name_plural': 'logs de páginas',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrivacySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('body', models.TextField(verbose_name='contenido')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'sección de privacidad',
                'verbose_name_plural': 'secciones de privacidad',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
            bases=(core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, core.mixin.models.CoverMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TermsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('body', models.TextField(verbose_name='contenido')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'sección de términos',
                'verbose_name_plural': 'secciones de términos',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
            bases=(core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, core.mixin.models.CoverMixin, models.Model),
        ),
    ]
