# Generated by Django 6.1 on 2026-09-17 17:50

import core.mixin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='asunto')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('READ', 'Leído'), ('REPLIED', 'Respondido'), ('ARCHIVED', 'Archivado'), ('SPAM', 'Spam')], default='NEW', max_length=12, verbose_name='estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'mensaje de contacto',
                'verbose_name_plural': 'mensajes de contacto',
                'ordering': ['-created_at'],
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='respuesta')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'respuesta de contacto',
                'verbose_name_plural': 'respuestas de contacto',
                'ordering': ['created_at'],
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='momento')),
                ('process', models.CharField(blank=True, max_length=255, verbose_name='proceso')),
                ('level', models.CharField(choices=[('NOT_SET', 'No establecido'), ('TRACE', 'Rastreo'), ('DEBUG', 'Depuración'), ('INFO', 'Información'), ('NOTICE', 'Aviso'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico'), ('FATAL', 'Error fatal'), ('ALERT', 'Alerta'), ('EMERGENCY', 'Emergencia')], default='INFO', max_length=10, verbose_name='nivel')),
                ('message', models.TextField(blank=True, verbose_name='mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'log de correo',
                'verbose_name_plural': 'logs de correo',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=320, verbose_name='destinatario')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='asunto')),
                ('body', models.TextField(blank=True, verbose_name='cuerpo enviado')),
                ('context', models.JSONField(blank=True, null=True, verbose_name='variables')),
                ('status', models.CharField(choices=[('SENT', 'Enviado'), ('QUEUED', 'En cola'), ('ERROR', 'Error'), ('SKIPPED', 'Omitido (sin plantilla)')], default='SENT', max_length=10, verbose_name='estado')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'correo',
                'verbose_name_plural': 'correos',
                'ordering': ['-created_at'],
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='clave')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('subject', models.CharField(max_length=255, verbose_name='asunto')),
                ('body_html', models.TextField(verbose_name='cuerpo (HTML)')),
                ('body_text', models.TextField(blank=True, verbose_name='cuerpo (texto plano)')),
                ('description', models.TextField(blank=True, verbose_name='notas / variables disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
            ],
            options={
                'verbose_name': 'plantilla de correo',
                'verbose_name_plural': 'plantillas de correo',
                'ordering': ['name'],
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_email', models.BooleanField(default=False, verbose_name='enviar correos')),
                ('signature', models.TextField(blank=True, verbose_name='firma')),
                ('from_email', models.CharField(blank=True, max_length=320, verbose_name='remitente (From)')),
                ('smtp_host', models.CharField(blank=True, max_length=200, verbose_name='SMTP host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP puerto')),
                ('smtp_user', models.CharField(blank=True, max_length=320, verbose_name='SMTP usuario')),
                ('smtp_password', models.CharField(blank=True, max_length=255, verbose_name='SMTP contraseña')),
                ('use_tls', models.BooleanField(default=True, verbose_name='usar TLS')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
            ],
            options={
                'verbose_name': 'configuración de correo',
                'verbose_name_plural': 'configuración de correo',
            },
            bases=(core.mixin.models.CoverMixin, core.mixin.models.DateDisplayMixin, core.mixin.models.BooleanDisplayMixin, models.Model),
        ),
    ]
